// src/features/crossAnalysis/copy.ts
export const crossCopy = {
  title: "Cross Analysis",
  subtitle: "在多份披露之间对齐口径，提炼可追溯的差异与趋势。",
  emptyTitle: "先选两份报告，再开始对比。",
  emptyBody: "回到报告列表，选择至少两份报告。我们会自动带上你已选的范围。",
  emptyCta: "返回报告选择",
  loadingTitle: "正在对齐披露口径…",
  loadingBody: "先呈现可用框架，内容会按报告逐步填充。",
  noDataTitle: "这组议题更像“文字披露”。",
  noDataBody: "暂未识别到稳定可比的数值口径。已为你保留相关文本线索，便于横向阅读。",
  disclaimerTitle: "口径提示",
  disclaimerBody: "单位/范围/年度可能存在差异。图表仅在可比区间展示，其余以摘要为准。",
  evidenceTitle: "Evidence",
  evidenceBody: "可追溯到原文页。我们只展示最关键的 1–3 条线索。",
  aiFab: "在对比中追问",
  aiTitle: "AI 对话",
  aiModeSingle: "对某一报告提问",
  aiModeCross: "跨报告提问",
  aiHint: "用一句话描述你想比较的重点。我们会在多个披露之间做对齐与汇总。",
  aiPickReport: "请选择一份报告",
  errorTitle: "这一页暂时没有打开。",
  errorBody: "可能是网络或数据源暂时不可用。我们已经保留你的选择范围。",
};
