import type { Metadata } from "next";
import { AntdRegistry as AntdStyleRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";
import HtmlLangSync from "@/i18n/HtmlLangSync";

export const metadata: Metadata = {
  title: "Euler ESG",
  description: "Generated by create next app",
  icons: {
    icon: "/Euler-Img.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN" suppressHydrationWarning>
      <body className="antialiased">
        <HtmlLangSync />
        <AntdStyleRegistry>
          <div id="root-layout">{children}</div>
        </AntdStyleRegistry>
      </body>
    </html>
  );
}
